### PR TITLE
Fix #37 Fix #12

### LINKED ISSUE #12: Run
The player runs and hides from the opponent, and goes to the outdoor menu.
 However, the opponent recovers all its HP, and will attack again if the
player does anything other than move away from the current square or exit the game.

### LINKED ISSUE #37: Add Rats

### PR DESCRIPTION
**Pull request by leethintsinjohn**
Added rats to the world and run function

CombatMenuFunctions.py
-Added missing error messages when moving out of map (For S and D key)
-Fixed some issues with attack() function that resulted in the player and rat healing to full hp everytime the function is called
-Changed some of the references in attack() function due to fix above

-Main.py
-Added rat as a global variable to introduce it to the world
-Added functions when moving to encounter rat
-Added run function

### CODE REVIEW

**Comment by leethintsinjohn** [comment]
@harithmdnoor I noticed an issue whereby the player does not die in combat should their hp hit 0 or lower.

**Comment by ETIOct2020Team3** [comment]
Issues:
When hero at 'K', program goes into a loop
Hero can kill rat even at < 0 hp

**Comment by leethintsinjohn** [comment]
> 
> 
> Issues:
> When hero at 'K', program goes into a loop
> Hero can kill rat even at < 0 hp

Thanks for pointing out the issue of the program looping when the hero reaches K. It is 'expected' as the requirements have not stated what should be printed / happen when the hero steps on the K tile, so the program loops as the while loop that prints all the menus has no elif statement to carry out if the hero is on a K tile. 
It will be addressed in my next build, which should have instructions on how to handle the hero stepping on the K tile.

**Comment by harithmdnoor** [comment]
@Nurhannanis can u create an issue to fix this bug?

**Pull request merged**
